### PR TITLE
Updated test for IE6

### PR DESCRIPTION
**Pull request by annybs**
for compatibility with jQuery 1.9+ as $.browser has been removed http://jquery.com/upgrade-guide/1.9/#jquery-browser-removed

### CODE REVIEW

**Comment by dubcanada** [comment]
I'd be interested in knowing what kind of support for IE6 people want. If jQuery is removing IE6 support. Should we follow suit considering we rely on jQuery? Upgrading parts of this library to new jQuery will break in IE6 anyways.

**Comment by buckwilson** [comment]
True. Even enterprise companies like Jive (who this plugin was made for in the outset) have abandoned IE6. 

However, I really like the fact that lbme is a workhorse that will take whatever you throw at it. 

You know, if it doesn't support IE6, lbme could probably become more CSS heavy (see the bare beginnings of this train of thought in modalme: https://github.com/buckwilson/Lightbox_me/tree/modalMe)

**Comment by davidkaufman** [comment]
We don't support ie6 either. So I personally don't care if lightbox_me does either -- or whether it beomes more css heavy or not.  I'd just like to see a new version of lbme released that doesn't throw errors when used with the latest jQuery.  That said, I must say I love lightbox_me!  I love that it is dead simple, I love that it is only ~200 lines long.  Thanks Buck!

**Comment by annybs** [comment]
Was just aimlessly clicking around github on a lazy Saturday afternoon and discovered that this pull request is still open...

Yeah, IE6 is pretty much totally dead now and anyone still supporting it most likely isn't going to use lightbox_me - but as I suggested the original commit message the patch is more to do with the deprecation of `jQuery.browser` in 1.9; I was using 1.9 in a client website and the jQuery-based user agent check would just trigger an uncaught exception and break functionality.

At the time I thought it was worth merging but perhaps the feature has been deprecated in @buckwilson master since; in any event perhaps it's worth closing this pull request now :p

**Pull request closed without merging**
