### PR TITLE
Compatibility with jQuery 1.9.1

### PR DESCRIPTION
**Pull request by ghost**
Compatible with jQuery 1.9.1 and not breaking IE6 compatibility (and nothing else hopefully)

### CODE REVIEW

**Comment by iRyusa** [comment]
+1 need to be merged !

**Comment by cabgfx** [comment]
:+1: I have this fix currently running on a site, have had no problems at all.

**Comment by guillep19** [comment]
I was going to post this issue and a fix until I saw this. 
It still needs to be merged :P

**Comment by buckwilson** [comment]
Thanks for doing this. Just went ahead and pulled IE6 support altogether. It kind of hurts to remove it, but then again it doesn’t... if someone feels particularly hurt, I can put it back and use this change to make lb_me compat. with the new jQueries.

**Pull request closed without merging**
